# Copyright 2025 Naked Software, LLC
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

name: golangci-lint

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/golangci-lint.yaml
      - src/authorization/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/golangci-lint.yaml
      - src/authorization/**

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'src/authorization/go.mod'
          cache-dependency-path: 'src/authorization/go.sum'
      - name: Lint Source Code
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: src/authorization